In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import KFold
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score,classification_report
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.tree import DecisionTreeClassifier

In [2]:
df = pd.read_csv('gaya_belajar_dataset.csv')

In [3]:
df

Q1  Q2  Q3  Q4  Q5  Q6  Q7  Q8  Q9  Q10       Label
0    1   1   0   0   1   0   1   0   1    1    Auditori
1    1   0   1   0   0   0   1   0   1    1      Visual
2    1   0   0   1   1   1   0   0   1    0  Kinestetik
3    1   1   0   1   1   1   0   0   0    0    Auditori
4    0   0   0   1   0   0   1   1   0    1    Auditori
5    1   0   0   1   0   0   1   0   1    0    Auditori
6    0   1   0   0   1   0   1   0   1    1    Auditori
7    1   0   0   1   0   0   0   1   0    0      Visual
8    1   0   1   1   0   1   0   0   1    1      Visual
9    0   1   1   1   1   1   1   1   0    1    Auditori
10   1   1   1   0   0   0   1   1   1    0      Visual
11   0   1   1   1   1   1   0   1   0    1    Auditori
12   0   1   1   1   0   1   0   0   1    0    Auditori
13   1   1   1   0   0   0   1   1   0    0      Visual
14   1   1   0   1   1   0   0   1   0    1    Auditori
15   0   1   1   1   1   1   1   0   1    1    Auditori
16   0   0   0   0   0   0   1   1   1    0      Visual
17   1   1   0   0   1   1   0   1   1    0  Kinestetik
18   1   1   0   0   0   1   1   1   1    1    Auditori
19   1   0   1   0   0   1   1   0   1    0      Visual
20   1   0   0   1   0   0   0   1   1    1      Visual
21   1   0   0   1   0   0   0   0   0    1    Auditori
22   1   1   0   1   0   1   0   0   1    1    Auditori
23   0   0   1   0   0   0   1   0   1    1    Auditori
24   0   0   0   1   1   0   1   1   0    0    Auditori
25   0   0   1   1   0   1   0   0   1    0  Kinestetik
26   0   1   0   0   0   1   0   1   0    1    Auditori
27   0   0   1   1   0   1   1   1   0    0      Visual
28   0   1   0   1   0   0   1   0   1    1    Auditori
29   0   1   1   0   0   0   0   0   0    0      Visual
30   1   0   1   0   1   1   1   0   1    0  Kinestetik
31   0   0   1   1   1   1   0   0   0    0  Kinestetik
32   0   0   0   0   0   1   0   1   1    0  Kinestetik
33   1   0   0   0   1   0   1   0   0    1    Auditori
34   0   0   1   1   1   0   1   1   1    0      Visual
35   1   0   0   1   0   0   0   0   1    1    Auditori
36   0   0   0   1   0   0   0   1   1    0      Visual
37   0   1   1   1   1   1   1   1   1    1    Auditori
38   1   1   0   1   0   1   1   0   1    0    Auditori
39   1   0   1   0   1   0   0   0   1    0      Visual
40   1   0   1   0   0   0   0   1   1    0      Visual
41   1   0   0   0   0   0   0   1   0    0      Visual
42   0   1   0   1   0   1   0   0   0    0    Auditori
43   0   0   0   0   0   0   0   1   1    1      Visual
44   0   1   0   1   1   0   0   0   0    1    Auditori
45   1   0   0   0   0   0   1   1   0    0      Visual
46   0   1   0   1   0   1   0   0   0    0    Auditori
47   1   0   0   0   0   1   0   0   1    1  Kinestetik
48   1   0   1   1   0   1   0   1   0    1      Visual
49   0   0   1   1   1   0   0   1   1    1      Visual

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Q1      50 non-null     int64 
 1   Q2      50 non-null     int64 
 2   Q3      50 non-null     int64 
 3   Q4      50 non-null     int64 
 4   Q5      50 non-null     int64 
 5   Q6      50 non-null     int64 
 6   Q7      50 non-null     int64 
 7   Q8      50 non-null     int64 
 8   Q9      50 non-null     int64 
 9   Q10     50 non-null     int64 
 10  Label   50 non-null     object
dtypes: int64(10), object(1)
memory usage: 4.4+ KB


In [5]:
x = df.drop("Label", axis=1) 
y = df["Label"]

In [6]:
y

0       Auditori
1         Visual
2     Kinestetik
3       Auditori
4       Auditori
5       Auditori
6       Auditori
7         Visual
8         Visual
9       Auditori
10        Visual
11      Auditori
12      Auditori
13        Visual
14      Auditori
15      Auditori
16        Visual
17    Kinestetik
18      Auditori
19        Visual
20        Visual
21      Auditori
22      Auditori
23      Auditori
24      Auditori
25    Kinestetik
26      Auditori
27        Visual
28      Auditori
29        Visual
30    Kinestetik
31    Kinestetik
32    Kinestetik
33      Auditori
34        Visual
35      Auditori
36        Visual
37      Auditori
38      Auditori
39        Visual
40        Visual
41        Visual
42      Auditori
43        Visual
44      Auditori
45        Visual
46      Auditori
47    Kinestetik
48        Visual
49        Visual
Name: Label, dtype: object

In [7]:
# Buat model Random Forest
model = RandomForestClassifier(n_estimators=100, random_state=42)

In [8]:
# Evaluasi dengan Stratified K-Fold
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
scores = cross_val_score(model, x, y, cv=skf, scoring='accuracy')

In [9]:
print("Akurasi tiap lipatan:", scores)
print(f"Rata-rata akurasi: {scores.mean():.2f}")
print(f"Standar deviasi: {scores.std():.2f}")

Akurasi tiap lipatan: [0.5 0.8 0.7 0.7 0.8]
Rata-rata akurasi: 0.70
Standar deviasi: 0.11


In [10]:
# Latih ulang model untuk simpan
import joblib
model.fit(x, y)
joblib.dump(model, "random_forest_gaya_belajar.pkl")

['random_forest_gaya_belajar.pkl']

In [11]:
# Prediksi untuk evaluasi dasar
y_pred = model.predict(x)
print("\nClassification Report:")
print(classification_report(y, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y, y_pred))


Classification Report:
              precision    recall  f1-score   support

    Auditori       1.00      1.00      1.00        24
  Kinestetik       1.00      1.00      1.00         7
      Visual       1.00      1.00      1.00        19

    accuracy                           1.00        50
   macro avg       1.00      1.00      1.00        50
weighted avg       1.00      1.00      1.00        50

Confusion Matrix:
[[24  0  0]
 [ 0  7  0]
 [ 0  0 19]]
